/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RomHacksIndexRouteImport } from './routes/rom-hacks/index'
import { Route as RomHacksRomHackSlugIndexRouteImport } from './routes/rom-hacks/$romHackSlug/index'
import { Route as RomHacksRomHackSlugPokemonsIndexRouteImport } from './routes/rom-hacks/$romHackSlug/pokemons/index'
import { Route as RomHacksRomHackSlugLocationsIndexRouteImport } from './routes/rom-hacks/$romHackSlug/locations/index'
import { Route as RomHacksRomHackSlugLocationsLocationSlugIndexRouteImport } from './routes/rom-hacks/$romHackSlug/locations/$locationSlug/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RomHacksIndexRoute = RomHacksIndexRouteImport.update({
  id: '/rom-hacks/',
  path: '/rom-hacks/',
  getParentRoute: () => rootRouteImport,
} as any)
const RomHacksRomHackSlugIndexRoute =
  RomHacksRomHackSlugIndexRouteImport.update({
    id: '/rom-hacks/$romHackSlug/',
    path: '/rom-hacks/$romHackSlug/',
    getParentRoute: () => rootRouteImport,
  } as any)
const RomHacksRomHackSlugPokemonsIndexRoute =
  RomHacksRomHackSlugPokemonsIndexRouteImport.update({
    id: '/rom-hacks/$romHackSlug/pokemons/',
    path: '/rom-hacks/$romHackSlug/pokemons/',
    getParentRoute: () => rootRouteImport,
  } as any)
const RomHacksRomHackSlugLocationsIndexRoute =
  RomHacksRomHackSlugLocationsIndexRouteImport.update({
    id: '/rom-hacks/$romHackSlug/locations/',
    path: '/rom-hacks/$romHackSlug/locations/',
    getParentRoute: () => rootRouteImport,
  } as any)
const RomHacksRomHackSlugLocationsLocationSlugIndexRoute =
  RomHacksRomHackSlugLocationsLocationSlugIndexRouteImport.update({
    id: '/rom-hacks/$romHackSlug/locations/$locationSlug/',
    path: '/rom-hacks/$romHackSlug/locations/$locationSlug/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rom-hacks/': typeof RomHacksIndexRoute
  '/rom-hacks/$romHackSlug/': typeof RomHacksRomHackSlugIndexRoute
  '/rom-hacks/$romHackSlug/locations/': typeof RomHacksRomHackSlugLocationsIndexRoute
  '/rom-hacks/$romHackSlug/pokemons/': typeof RomHacksRomHackSlugPokemonsIndexRoute
  '/rom-hacks/$romHackSlug/locations/$locationSlug/': typeof RomHacksRomHackSlugLocationsLocationSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rom-hacks': typeof RomHacksIndexRoute
  '/rom-hacks/$romHackSlug': typeof RomHacksRomHackSlugIndexRoute
  '/rom-hacks/$romHackSlug/locations': typeof RomHacksRomHackSlugLocationsIndexRoute
  '/rom-hacks/$romHackSlug/pokemons': typeof RomHacksRomHackSlugPokemonsIndexRoute
  '/rom-hacks/$romHackSlug/locations/$locationSlug': typeof RomHacksRomHackSlugLocationsLocationSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rom-hacks/': typeof RomHacksIndexRoute
  '/rom-hacks/$romHackSlug/': typeof RomHacksRomHackSlugIndexRoute
  '/rom-hacks/$romHackSlug/locations/': typeof RomHacksRomHackSlugLocationsIndexRoute
  '/rom-hacks/$romHackSlug/pokemons/': typeof RomHacksRomHackSlugPokemonsIndexRoute
  '/rom-hacks/$romHackSlug/locations/$locationSlug/': typeof RomHacksRomHackSlugLocationsLocationSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/rom-hacks/'
    | '/rom-hacks/$romHackSlug/'
    | '/rom-hacks/$romHackSlug/locations/'
    | '/rom-hacks/$romHackSlug/pokemons/'
    | '/rom-hacks/$romHackSlug/locations/$locationSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/rom-hacks'
    | '/rom-hacks/$romHackSlug'
    | '/rom-hacks/$romHackSlug/locations'
    | '/rom-hacks/$romHackSlug/pokemons'
    | '/rom-hacks/$romHackSlug/locations/$locationSlug'
  id:
    | '__root__'
    | '/'
    | '/rom-hacks/'
    | '/rom-hacks/$romHackSlug/'
    | '/rom-hacks/$romHackSlug/locations/'
    | '/rom-hacks/$romHackSlug/pokemons/'
    | '/rom-hacks/$romHackSlug/locations/$locationSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RomHacksIndexRoute: typeof RomHacksIndexRoute
  RomHacksRomHackSlugIndexRoute: typeof RomHacksRomHackSlugIndexRoute
  RomHacksRomHackSlugLocationsIndexRoute: typeof RomHacksRomHackSlugLocationsIndexRoute
  RomHacksRomHackSlugPokemonsIndexRoute: typeof RomHacksRomHackSlugPokemonsIndexRoute
  RomHacksRomHackSlugLocationsLocationSlugIndexRoute: typeof RomHacksRomHackSlugLocationsLocationSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rom-hacks/': {
      id: '/rom-hacks/'
      path: '/rom-hacks'
      fullPath: '/rom-hacks/'
      preLoaderRoute: typeof RomHacksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rom-hacks/$romHackSlug/': {
      id: '/rom-hacks/$romHackSlug/'
      path: '/rom-hacks/$romHackSlug'
      fullPath: '/rom-hacks/$romHackSlug/'
      preLoaderRoute: typeof RomHacksRomHackSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rom-hacks/$romHackSlug/pokemons/': {
      id: '/rom-hacks/$romHackSlug/pokemons/'
      path: '/rom-hacks/$romHackSlug/pokemons'
      fullPath: '/rom-hacks/$romHackSlug/pokemons/'
      preLoaderRoute: typeof RomHacksRomHackSlugPokemonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rom-hacks/$romHackSlug/locations/': {
      id: '/rom-hacks/$romHackSlug/locations/'
      path: '/rom-hacks/$romHackSlug/locations'
      fullPath: '/rom-hacks/$romHackSlug/locations/'
      preLoaderRoute: typeof RomHacksRomHackSlugLocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rom-hacks/$romHackSlug/locations/$locationSlug/': {
      id: '/rom-hacks/$romHackSlug/locations/$locationSlug/'
      path: '/rom-hacks/$romHackSlug/locations/$locationSlug'
      fullPath: '/rom-hacks/$romHackSlug/locations/$locationSlug/'
      preLoaderRoute: typeof RomHacksRomHackSlugLocationsLocationSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RomHacksIndexRoute: RomHacksIndexRoute,
  RomHacksRomHackSlugIndexRoute: RomHacksRomHackSlugIndexRoute,
  RomHacksRomHackSlugLocationsIndexRoute:
    RomHacksRomHackSlugLocationsIndexRoute,
  RomHacksRomHackSlugPokemonsIndexRoute: RomHacksRomHackSlugPokemonsIndexRoute,
  RomHacksRomHackSlugLocationsLocationSlugIndexRoute:
    RomHacksRomHackSlugLocationsLocationSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
